create table public.connections (
  id bigint generated by default as identity not null,
  requester_id uuid not null,
  addressee_id uuid not null,
  status public.connection_status not null default 'pending'::connection_status,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint connections_pkey primary key (id),
  constraint unique_connection_pair unique (requester_id, addressee_id),
  constraint connections_addressee_id_fkey foreign KEY (addressee_id) references profiles (id) on delete CASCADE,
  constraint connections_requester_id_fkey foreign KEY (requester_id) references profiles (id) on delete CASCADE,
  constraint check_not_self check ((requester_id <> addressee_id))
) TABLESPACE pg_default;

--TYPE public.connection_status AS ENUM (
--  'pending',
--  'accepted',
--  'declined',
--  'blocked'
--);