-- Missing schema for the Meet Riders app.
-- Run this in the Supabase SQL editor to bring the database in sync with the app code.

-- 1. profiles.student_type column (hosteller / dayscholar)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS student_type text null;

-- 2. ratings table
CREATE TABLE IF NOT EXISTS public.ratings (
  id bigint generated by default as identity not null,
  rater_id uuid not null,
  rated_user_id uuid not null,
  party_id uuid not null,
  score integer not null check (score between 1 and 5),
  comment text null,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint ratings_pkey primary key (id),
  constraint ratings_rater_id_fkey foreign key (rater_id) references public.profiles(id) on delete cascade,
  constraint ratings_rated_user_id_fkey foreign key (rated_user_id) references public.profiles(id) on delete cascade,
  constraint ratings_party_id_fkey foreign key (party_id) references public.parties(id) on delete cascade,
  constraint ratings_unique_per_rater unique (rater_id, rated_user_id, party_id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_ratings_rated_user ON public.ratings(rated_user_id);
CREATE INDEX IF NOT EXISTS idx_ratings_rater ON public.ratings(rater_id);

ALTER TABLE public.ratings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read ratings" ON public.ratings;
CREATE POLICY "Anyone can read ratings" ON public.ratings
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Users can insert their own ratings" ON public.ratings;
CREATE POLICY "Users can insert their own ratings" ON public.ratings
  FOR INSERT TO authenticated
  WITH CHECK (rater_id = auth.uid());

-- 3. user_locations table (live map + mutual-activity notifications)
CREATE TABLE IF NOT EXISTS public.user_locations (
  user_id uuid not null,
  latitude double precision not null,
  longitude double precision not null,
  last_updated timestamp with time zone not null default timezone('utc'::text, now()),
  constraint user_locations_pkey primary key (user_id),
  constraint user_locations_user_id_fkey foreign key (user_id) references public.profiles(id) on delete cascade
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_user_locations_last_updated ON public.user_locations(last_updated);

ALTER TABLE public.user_locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read user locations" ON public.user_locations;
CREATE POLICY "Anyone can read user locations" ON public.user_locations
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Users can upsert their own location" ON public.user_locations;
CREATE POLICY "Users can upsert their own location" ON public.user_locations
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can update their own location" ON public.user_locations;
CREATE POLICY "Users can update their own location" ON public.user_locations
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- 4. reports table
CREATE TABLE IF NOT EXISTS public.reports (
  id bigint generated by default as identity not null,
  reporter_id uuid not null,
  reported_user_id uuid not null,
  reason text not null,
  details text null,
  party_id uuid null,
  status text not null default 'pending',
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint reports_pkey primary key (id),
  constraint reports_reporter_id_fkey foreign key (reporter_id) references public.profiles(id) on delete cascade,
  constraint reports_reported_user_id_fkey foreign key (reported_user_id) references public.profiles(id) on delete cascade,
  constraint reports_party_id_fkey foreign key (party_id) references public.parties(id) on delete cascade
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_reports_reporter ON public.reports(reporter_id);
CREATE INDEX IF NOT EXISTS idx_reports_reported ON public.reports(reported_user_id);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read their own reports" ON public.reports;
CREATE POLICY "Users can read their own reports" ON public.reports
  FOR SELECT TO authenticated
  USING (reporter_id = auth.uid());

DROP POLICY IF EXISTS "Users can insert their own reports" ON public.reports;
CREATE POLICY "Users can insert their own reports" ON public.reports
  FOR INSERT TO authenticated
  WITH CHECK (reporter_id = auth.uid());

-- 5. Fix infinite recursion in ride_history / ride_history_participants RLS policies.
-- The old participants policy queried ride_history, whose policy queried ride_history_participants,
-- causing "infinite recursion detected in policy for relation 'ride_history_participants'".
CREATE OR REPLACE FUNCTION public.is_ride_history_participant(p_history_id uuid, p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.ride_history_participants
    WHERE ride_history_id = p_history_id
      AND user_id = p_user_id
  );
$$;

DROP POLICY IF EXISTS "Users can view their ride history" ON public.ride_history;
CREATE POLICY "Users can view their ride history" ON public.ride_history
  FOR SELECT TO authenticated
  USING (
    public.is_ride_history_participant(ride_history.id, auth.uid())
  );

DROP POLICY IF EXISTS "Users can view history participants" ON public.ride_history_participants;
CREATE POLICY "Users can view history participants" ON public.ride_history_participants
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()
    OR public.is_ride_history_participant(ride_history_participants.ride_history_id, auth.uid())
  );

GRANT EXECUTE ON FUNCTION public.is_ride_history_participant(uuid, uuid) TO authenticated;

-- 6. get_party_route_savings RPC (exists in ride_history.sql but was never deployed;
-- used by LivePartyScreen.buildSavingsMessage, which currently swallows the 404)
DROP FUNCTION IF EXISTS public.get_party_route_savings(uuid);
CREATE OR REPLACE FUNCTION public.get_party_route_savings(
  p_party_id uuid
)
RETURNS TABLE (
  distance_saved_km double precision,
  time_saved_minutes double precision,
  baseline_km double precision,
  optimized_km double precision,
  baseline_minutes double precision,
  optimized_minutes double precision
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.route_distance_saved_km,
    p.route_time_saved_minutes,
    p.route_baseline_km,
    p.route_optimized_km,
    p.route_baseline_minutes,
    p.route_optimized_minutes
  FROM public.parties p
  WHERE p.id = p_party_id
    AND public.can_user_view_party_members(p.id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_party_route_savings(uuid) TO authenticated;