create table public.parties (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  host_id uuid not null,
  party_size integer not null,
  meetup_point text not null,
  drop_off text not null,
  is_friends_only boolean not null default false,
  is_gender_only boolean not null default false,
  ride_options text[] not null,
  expires_in text not null,
  expiry_timestamp timestamp with time zone not null,
  host_university text null,
  display_university text null,
  is_active boolean null,
  constraint parties_pkey primary key (id),
  constraint parties_host_id_fkey foreign KEY (host_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;