create table public.profiles (
  id uuid not null,
  full_name text null,
  major text null,
  bio text null,
  updated_at timestamp with time zone null,
  gender text null,
  ideal_departure_time text null,
  ideal_location text null,
  nickname text null,
  punctuality text null,
  birth_date date null,
  location text null,
  avatar_url text null,
  points integer null default 0,
  university text null,
  created_at timestamp with time zone null default now(),
  show_university boolean null default true,
  "isGenderOnly" boolean null,
  "rideOptions" text null,
  "expiresIn" text null,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;