/*
 * This source file was generated by the Gradle 'init' task
 */
package dbms;

public class App {
    public static void main(String[] args) {
        int[] arr = { 1, 2, 3,4,5,6};
        for (int i = 0; i < 6; i++) {
            if (i % 2 == 0) {
                arr[i] = 0;
            }
        }
        for(int i: arr)
        {System.out.print(i+", ");}
        System.err.println();
    }
}
